var list = [
    {
        id:0,
        title:'IV' ,
        text:'IV was the best memory every. Everyone sitting around the bonfire singing and playing. ',
        sign:'K' ,
    },
    {
        id:1,
        title:'IV' ,
        text:'IV',
        sign:'Chakri' ,
    },
    {
        id:2,
        title:'Wayanad Trip' ,
        text:'Wayanad trip in the first year with my roommate sachin and some friends of other branch, that trip  was simply hilarious, I never had that much of fun in a trip before.',
        sign:'Rajjo' ,
    },
    {
        id:3,
        title:'NITC' ,
        text:'I\'m blessed to get in NITC. ',
        sign:'Mallu' ,
    },
    {
        id:4,
        title:'Techweek' ,
        text:'Basith lighting firecrackers on techweek when they announced EEE won. The firecrackers were supposed to be lit when they announced CSE got second place. ',
        sign:'Sreeganesh' ,
    },
    {
        id:5,
        title:'LSD' ,
        text:'love, study, dream',
        sign:'Shelton' ,
    },
    {
        id:6,
        title:'College' ,
        text:'Dear juniors , I truly wish you guys to get back to college ( Shangri ) soon. Adios - BharaDwaj',
        sign:'BharaDwaj Ayinapurapu  a.k.a  BD' ,
    },
    {
        id:7,
        title:'IPL' ,
        text:'Watching ipl with friends in TV room in pg1 hostel',
        sign:'Vivek' ,
    },
    {
        id:8,
        title:'Night Cricket' ,
        text:'Night cricket in Basketball court, trips with friends, fests and fun.',
        sign:'Srivatsa Pillutla' ,
    },
    {
        id:9,
        title:'Online Sem' ,
        text:'Online sem sucks, but no college from now sucks even more :)',
        sign:'Nikhil Hulle' ,
    },
    {
        id:10,
        title:'First year' ,
        text:'Relief from all the coaching classes.The standout moment for me had to be the short film that our class shot. Also it was the first time you get to taste being independent.',
        sign:'Mohammed Rizwan' ,
    },
    {
        id:11,
        title:'Second year' ,
        text:'Truth be told it was a bit rocky . The learning curve was a bit high . I would advise all to be patient . 2nd year wasn\'t so hard for many of my friends , so I guess it\'s more an individualistic thing.',
        sign:'Mohammed Rizwan' ,
    },
    {
        id:12,
        title:'Third year' ,
        text:'I decided to join Hockey Team . Let me tell you that it was awesome . Still puts a smile on my face.',
        sign:'Mohammed Rizwan' ,
    },
    {
        id:13,
        title:'Fourth year' ,
        text:'This is the year I learned the importance of compassion and helping mentality . An understanding that wisdom and knowledge is different .',
        sign:'Mohammed Rizwan' ,
    },
    {
        id:14,
        title:'Overall' ,
        text:'I am so lucky to meet so many good people of the same wavelength . I thank you NITC.',
        sign:'Mohammed Rizwan' ,
    },
    {
        id:15,
        title:'Sparrow' ,
        text:'I went to house of sparrow after "that" incident so many times Alone',
        sign:'Kuruvi' ,
    },
    {
        id:16,
        title:'Friends' ,
        text:'I made good friends.',
        sign:'Rayhan' ,
    },
    {
        id:17,
        title:'IV' ,
        text:'IV was the best. Charades in bus and waterfalls were amazing',
        sign:'K' ,
    },
    {
        id:18,
        title:'Pamb' ,
        text:'One time when I was the greatest pamb at shangri',
        sign:'Alan Thomas' ,
    },
    {
        id:19,
        title:'Noodles' ,
        text:'Schezwan noodles, xtra spicy. Will be missed.',
        sign:'Ummu Kulsu' ,
    },
    {
        id:20,
        title:'Best Faculty' ,
        text:'Best faculty award goes to Jay Prakash sir',
        sign:'Njn Anonymous' ,
    },
    {
        id:21,
        title:'Onam And IV' ,
        text:'Cse events like onam and IV were a blast',
        sign:'Jk' ,
    },
    {
        id:22,
        title:'Get Ready' ,
        text:'Get ready to face the war my dear colleagues n juniors 😍',
        sign:'Chinna' ,
    },
    {
        id:23,
        title:'Ragam' ,
        text:'Ragam 2019.',
        sign:'Rahul' ,
    },
    {
        id:24,
        title:'9 lakg mAh' ,
        text:'Do you know that there exist a 9 lakh mAh battery..... If you don\'t know kindly ask nikhil nath R',
        sign:'9 lakh mAh' ,
    },
    {
        id:25,
        title:'IV' ,
        text:'From the bottom of my heart, truly memorable and soul-fulfilled journey with IV being the favourite memory. (No Lame Joke here) Only regret is missing those beautiful 1.25 years in the college at the end.',
        sign:'Hemanth Varma' ,
    },
    {
        id:26,
        title:'Live life' ,
        text:'Live life',
        sign:'Snyder' ,
    },
    {
        id:27,
        title:'Onam' ,
        text:'Onam celebration ♥️♥️',
        sign:'Hi' ,
    },
    {
        id:28,
        title:'Enjoy' ,
        text:'Enjoy well, forget abt classes',
        sign:'ThuGg' ,
    },
    {
        id:29,
        title:'IV' ,
        text:'IV',
        sign:'Haha' ,
    },
    {
        id:30,
        title:'Lit' ,
        text:'Lit the shit',
        sign:'Captain Poonia' ,
    },
    {
        id:31,
        title:'Mono Act' ,
        text:'MonoAction from 10Pm-12 am on Dec 31st 2018 at Archi department... It was really fun❤️',
        sign:'283' ,
    },
    {
        id:32,
        title:'LD Lab' ,
        text:'We have done some epic Shit together like mass bunk on an evaluation(LD Lab). ',
        sign:'Ronny' ,
    },
    {
        id:33,
        title:'5/10' ,
        text:'5/10 college life ¯\_(ツ)_/¯',
        sign:'ᕙ(  • ‿ •  )ᕗ' ,
    },
    {
        id:34,
        title:'Late Nights' ,
        text:'All those late night conversations inside the hostel and unplanned trips ❤️.',
        sign:'Harijothis' ,
    },
    {
        id:35,
        title:'Onam and IV' ,
        text:'CSEA Onam and IV was amazing. Bonfires, Goa and waterfalls were are so fun and beautiful. ',
        sign:'KK' ,
    },
    {
        id:36,
        title:'Onam and IV' ,
        text:'The Entire IV. The only CSE ONAM.(Not) Attending class :)',
        sign:'Reproduce my last dialogue' ,
    },
    {
        id:37,
        title:'IV' ,
        text:'IV',
        sign:'Novel implementation' ,
    },
    {
        id:38,
        title:'First Hours' ,
        text:'Never attending first hours',
        sign:'Eduserver' ,
    },
    {
        id:39,
        title:'IV and Onam' ,
        text:'IV and CSE onam :))',
        sign:'S Grade' ,
    },
    {
        id:40,
        title:'Love Story' ,
        text:'The greatest love story i have seen in my life is bharadwaj and quatar papa',
        sign:'Suhas' ,
    },
    {
        id:41,
        title:'Memorable' ,
        text:'I am just grateful to spend these 4 years of my life surrounded with such an awesome group of people. The time I spent with my friends is most memorable for me.',
        sign:'Sachin' ,
    },
    {
        id:42,
        title:'Coffee' ,
        text:'Dear juniors, sleep well, you can save a lot of money taking 35Rs per cold coffee.',
        sign:'Sreekar' ,
    },
    {
        id:43,
        title:'Wing man' ,
        text:'Please spread this as much as possible, i want to help my friend out.K---- has a crush on harikrishnan, and this is the last opportunity to let this be known, as she is not going to confess on her own.',
        sign:'Skv' ,
    },
    {
        id:44,
        title:'Wing Man 2.0' ,
        text:'I would like this occasion to put forward the unrequited love of K---- towards Harikrishnan. ',
        sign:'💀' ,
    },
    {
        id:45,
        title:'Wing Man 3.0' ,
        text:'College mothathil pwoliyallee........Pinne oru Karyam enthaachaa aaa paavam K----kk Harikrishnane ishtaaan...Avalkk ath parayaanum kazhiyunnilla...Onn aarenkilum aa paavngalee Help cheyyooo',
        sign:'Muneef' ,
    },
    {
        id:46,
        title:'Wing Man 4.0 ?' ,
        text:'Helping a friend out in this last moment or this might probably never come out.K---- has a crush on Harikrishnan and she has gone past the deadline to confess this. We, responsible friends, are helping her out. ',
        sign:'Sid' ,
    },
    {
        id:47,
        title:'Professors' ,
        text:'Been quite a ride, gained a lot of space to grow. Even though not all professors are good, a few have genuinely helped me so much that I couldn\'t thank them enough.',
        sign:'ProfessorJimMoriarty' ,
    },
    {
        id:48,
        title:'Teachers' ,
        text:'I want to mention Dr. Subhasree for teaching me always to keep trying, Dr. Jayaraj for teaching me that there\'s always a second chance and Dr. Lijiya for teaching me that there\'s no shortcut to success.',
        sign:'ProfessorJimMoriarty' ,
    },
    {
        id:49,
        title:'Advice' ,
        text:'Made friends for life. Learned tons of lessons from seniors and classmates. A message to juniors: Never be afraid to admit that you\'re wrong. You can never know enough of anything, so keep learning.',
        sign:'ProfessorJimMoriarty' ,
    },
    {
        id:50,
        title:'OAT' ,
        text:'Favourite memory - Chillin in OAT ',
        sign:'Lalala' ,
    },
    {
        id:51,
        title:'Nobara' ,
        text:'Confession : Roses are red, Violets are blue, I\'m a simp for my queen - Nobara Kugisaki. hehe <3 Favorite Memory: 2 words. IV Goa',
        sign:'KSI\'s forehead' ,
    },
    {
        id:52,
        title:'Sidharth Anil' ,
        text:'I would like share my happiness through this platform.My frnd Sidharth Anil has a huge crush on Shabin from the very beginning.As the time passed,his love got reciprocated.So I wish them a veryyyy good luck for their future.',
        sign:'Anonymous' ,
    },
    {
        id:53,
        title:'IV and Trips' ,
        text:'I would say the best memory of my clg life is the time when we went for IV because what i understood at the end of my clg life is everything u did in the clg matters but memories matters a lot.Be it IV or clg trips just try to explore kerala as much as you can.',
        sign:'Chacha' ,
    },
    {
        id:54,
        title:'Enjoy' ,
        text:'There is a quote that "Try to live every day of your life in the best possible way", so I can say that clg is somewhat move around this quote bcz there is not a single bad day. ',
        sign:'Chacha' ,
    },
    {
        id:55,
        title:'Project and Rajpath' ,
        text:'The biggest fear I ever had is the "Major Project" but everything pass on as the time pass so is the major project.Be Careful when u are walking on Rajpath (lol).',
        sign:'Chacha' ,
    },
    {
        id:56,
        title:'dc++' ,
        text:'Start a dc++ community.',
        sign:'NEVADA GetForce' ,
    },
    {
        id:57,
        title:'Challenge yourself' ,
        text:'Constantly challenge yourself',
        sign:'Anup Kumar' ,
    },
    {
        id:58,
        title:'Ragam' ,
        text:'Ragam',
        sign:'Naveen Teja' ,
    },
];